### PR TITLE
[feature #161036505] created login page

### PR DESCRIPTION
**Pull request by unah254**
#### What does this PR do?
Creates the login page
#### Description of Task to be completed?
Users should be able to login into the application
#### How should this be manually tested?
After cloning the repo using `git clone https://github.com/unah254/Store-Manager.git`
cd into it and open the login.html file using your favorite browser
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
[#161036505](url)
#### Screenshots (if appropriate)
loginpage

### CODE REVIEW

**Comment by wandesky** [comment]
Is it possible to add a navbar at the top and possibly a logo?

**Review by wandesky — COMMENTED** [review]
Consider adding a navbar and a logo.

**Comment by davishooly** [comment]
good UI,, add navbar

**Comment by danielotieno** [comment]
Awesome UI... Consider doing what the above colleagues mentioned

**Pull request merged**
